<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>DecaEngine.Input.Sdl3._0</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Evergine.Mathematics" Version="2026.5.26.372" />
      <PackageReference Include="ppy.SDL3-CS" Version="2026.429.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\DecaEngine.Core\DecaEngine.Core.csproj" />
      <ProjectReference Include="..\DecaEngine.Input.Core\DecaEngine.Input.Core.csproj" />
      <ProjectReference Include="..\DecaEngine.Sdl3\DecaEngine.Sdl3.csproj" />
    </ItemGroup>

</Project>
