<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
		<EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
    </PropertyGroup>
	
    <ItemGroup>
        <ProjectReference Include="..\DecaEngine.Generator\DecaEngine.Generator.csproj" 
            OutputItemType="Analyzer" 
            ReferenceOutputAssembly="false"/>
    </ItemGroup>
	
</Project>
