<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
		<EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>
	
    <ItemGroup>
        <ProjectReference Include="..\DecaEngine.Generator\DecaEngine.Generator.csproj" 
            OutputItemType="Analyzer" 
            ReferenceOutputAssembly="false"/>
    </ItemGroup>
	
</Project>
