<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>Engine.ImGui.Core</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Evergine.Mathematics" Version="2026.5.26.372" />
      <PackageReference Include="Hexa.NET.ImGui" Version="2.2.10-prerelease" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\DecaEngine.Core\DecaEngine.Core.csproj" />
      <ProjectReference Include="..\DecaEngine.Graphics.Core\DecaEngine.Graphics.Core.csproj" />
      <ProjectReference Include="..\DecaEngine.Input.Core\DecaEngine.Input.Core.csproj" />
    </ItemGroup>

</Project>
