<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>DecaEngine.Sdl</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Evergine.Mathematics" Version="2026.5.26.372" />
      <PackageReference Include="ppy.SDL3-CS" Version="2026.429.0" />
      <PackageReference Include="StbImageSharp" Version="2.30.15" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\DecaEngine.Core\DecaEngine.Core.csproj" />
    </ItemGroup>

</Project>
