<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <RootNamespace>DecaEngine.Graphics</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\DecaEngine.Core\DecaEngine.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Alimer.Bindings.MeshOptimizer" Version="1.2.1" />
      <PackageReference Include="BCnEncoder.Net" Version="2.3.0" />
      <PackageReference Include="Evergine.Mathematics" Version="2026.5.26.372" />
      <PackageReference Include="Friflo.Engine.ECS" Version="4.0.0-preview.2" />
      <PackageReference Include="SharpGLTF.Core" Version="1.0.6" />
      <PackageReference Include="SharpGLTF.Runtime" Version="1.0.6" />
      <PackageReference Include="SharpGLTF.Toolkit" Version="1.0.6" />
      <PackageReference Include="StbImageSharp" Version="2.30.15" />
    </ItemGroup>

</Project>
