<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>DecaEngine.Input</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\DecaEngine.Core\DecaEngine.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Evergine.Mathematics" Version="2026.5.26.372" />
    </ItemGroup>

</Project>
