public static class KeyboardKeys
{
	public enum Keys
	{
		Backspace,
		Tab,
		Return,
		Escape,
		Space,
		Exclamation,
		Quotation,
		NumberSign,
		Dollar,
		Percent,
		Ampersand,
		SingleQuote,
		LeftParen,
		RightParen,
		Asterisk,
		Plus,
		Comma,
		Minus,
		Period,
		Slash,
		Digit0,
		Digit1,
		Digit2,
		Digit3,
		Digit4,
		Digit5,
		Digit6,
		Digit7,
		Digit8,
		Digit9,
		Colon,
		Semicolon,
		LessThan,
		Equal,
		GreaterThan,
		Question,
		At,
		LeftBracket,
		Backslash,
		RightBracket,
		Caret,
		Underscore,
		Backtick,
		A,
		B,
		C,
		D,
		E,
		F,
		G,
		H,
		I,
		J,
		K,
		L,
		M,
		N,
		O,
		P,
		Q,
		R,
		S,
		T,
		U,
		V,
		W,
		X,
		Y,
		Z,
		LeftBrace,
		Pipe,
		RightBrace,
		Tilde,
		Delete,
		PlusMinus,
		LeftTab,
		Level5Shift,
		MultiKeyCompose,
		LeftMeta,
		RightMeta,
		LeftHyper,
		RightHyper,
		CapsLock,
		F1,
		F2,
		F3,
		F4,
		F5,
		F6,
		F7,
		F8,
		F9,
		F10,
		F11,
		F12,
		PrintScreen,
		ScrollLock,
		Pause,
		Insert,
		Home,
		PageUp,
		End,
		PageDown,
		Right,
		Left,
		Down,
		Up,
		NumLock,
		KeypadSlash,
		KeypadAsterisk,
		KeypadMinus,
		KeypadPlus,
		KeypadEnter,
		Keypad1,
		Keypad2,
		Keypad3,
		Keypad4,
		Keypad5,
		Keypad6,
		Keypad7,
		Keypad8,
		Keypad9,
		Keypad0,
		KeypadDot,
		Menu,
		Power,
		KeypadEqual,
		F13,
		F14,
		F15,
		F16,
		F17,
		F18,
		F19,
		F20,
		F21,
		F22,
		F23,
		F24,
		Execute,
		Help,
		Select,
		Stop,
		Again,
		Undo,
		Cut,
		Copy,
		Paste,
		Find,
		Mute,
		VolumeUp,
		VolumeDown,
		KeypadComma,
		KeypadEqualsAs400,
		AltErase,
		SysReq,
		Cancel,
		Clear,
		Prior,
		Separator,
		Out,
		Oper,
		ClearAgain,
		Csel,
		Exsel,
		Keypad00,
		Keypad000,
		ThousandsSeparator,
		DecimalSeparator,
		CurrencyUnit,
		CurrencySubUnit,
		KeypadLeftParen,
		KeypadRightParen,
		KeypadLeftBrace,
		KeypadRightBrace,
		KeypadTab,
		KeypadBackspace,
		KeypadA,
		KeypadB,
		KeypadC,
		KeypadD,
		KeypadE,
		KeypadF,
		KeypadXor,
		KeypadCaret,
		KeypadPercent,
		KeypadLessThan,
		KeypadGreaterThan,
		KeypadAnd,
		KeypadAndAnd,
		KeypadPipe,
		KeypadPipePipe,
		KeypadColon,
		KeypadHash,
		KeypadSpace,
		KeypadAt,
		KeypadExclamation,
		KeypadMemStore,
		KeypadMemRecall,
		KeypadMemClear,
		KeypadMemAdd,
		KeypadMemSubtract,
		KeypadMemMultiply,
		KeypadMemDivide,
		KeypadPlusMinus,
		KeypadClear,
		KeypadClearEntry,
		KeypadBinary,
		KeypadOctal,
		KeypadDecimal,
		KeypadHex,
		LeftCtrl,
		LeftShift,
		LeftAlt,
		LeftWindows,
		RightCtrl,
		RightShift,
		RightAlt,
		RightWindows,
		ModeSwitch,
		Sleep,
		Wake,
		ChannelUp,
		ChannelDown,
		MediaPlay,
		MediaPause,
		MediaRecord,
		MediaFastForward,
		MediaRewind,
		MediaTrackNext,
		MediaTrackPrevious,
		MediaStop,
		Eject,
		MediaPlayPause,
		MediaSelect,
		AcNew,
		AcOpen,
		AcClose,
		AcExit,
		AcSave,
		AcPrint,
		AcProperties,
		AcSearch,
		AcHome,
		AcBack,
		AcForward,
		AcStop,
		AcRefresh,
		AcBookmarks,
		SoftLeft,
		SoftRight,
		Call,
		EndCall,
		All,
		LastKeyChar
	}

	public static readonly Dictionary<string, Keys> KeyNameDictionary = new()
	{
		{ "Backspace", Keys.Backspace },
		{ "Tab", Keys.Tab },
		{ "Return", Keys.Return },
		{ "Escape", Keys.Escape },
		{ "Space", Keys.Space },
		{ "!", Keys.Exclamation },
		{ "\"", Keys.Quotation },
		{ "#", Keys.NumberSign },
		{ "$", Keys.Dollar },
		{ "%", Keys.Percent },
		{ "&", Keys.Ampersand },
		{ "'", Keys.SingleQuote },
		{ "(", Keys.LeftParen },
		{ ")", Keys.RightParen },
		{ "*", Keys.Asterisk },
		{ "+", Keys.Plus },
		{ ",", Keys.Comma },
		{ "-", Keys.Minus },
		{ ".", Keys.Period },
		{ "/", Keys.Slash },
		{ "0", Keys.Digit0 },
		{ "1", Keys.Digit1 },
		{ "2", Keys.Digit2 },
		{ "3", Keys.Digit3 },
		{ "4", Keys.Digit4 },
		{ "5", Keys.Digit5 },
		{ "6", Keys.Digit6 },
		{ "7", Keys.Digit7 },
		{ "8", Keys.Digit8 },
		{ "9", Keys.Digit9 },
		{ ":", Keys.Colon },
		{ ";", Keys.Semicolon },
		{ "<", Keys.LessThan },
		{ "=", Keys.Equal },
		{ ">", Keys.GreaterThan },
		{ "?", Keys.Question },
		{ "@", Keys.At },
		{ "[", Keys.LeftBracket },
		{ "\\", Keys.Backslash },
		{ "]", Keys.RightBracket },
		{ "^", Keys.Caret },
		{ "_", Keys.Underscore },
		{ "`", Keys.Backtick },
		{ "A", Keys.A },
		{ "B", Keys.B },
		{ "C", Keys.C },
		{ "D", Keys.D },
		{ "E", Keys.E },
		{ "F", Keys.F },
		{ "G", Keys.G },
		{ "H", Keys.H },
		{ "I", Keys.I },
		{ "J", Keys.J },
		{ "K", Keys.K },
		{ "L", Keys.L },
		{ "M", Keys.M },
		{ "N", Keys.N },
		{ "O", Keys.O },
		{ "P", Keys.P },
		{ "Q", Keys.Q },
		{ "R", Keys.R },
		{ "S", Keys.S },
		{ "T", Keys.T },
		{ "U", Keys.U },
		{ "V", Keys.V },
		{ "W", Keys.W },
		{ "X", Keys.X },
		{ "Y", Keys.Y },
		{ "Z", Keys.Z },
		{ "{", Keys.LeftBrace },
		{ "|", Keys.Pipe },
		{ "}", Keys.RightBrace },
		{ "~", Keys.Tilde },
		{ "Delete", Keys.Delete },
		{ "±", Keys.PlusMinus },

		{ "LeftTab", Keys.LeftTab },
		{ "Level5Shift", Keys.Level5Shift },
		{ "MultiKeyCompose", Keys.MultiKeyCompose },
		{ "Left Meta", Keys.LeftMeta },
		{ "Right Meta", Keys.RightMeta },
		{ "Left Hyper", Keys.LeftHyper },
		{ "Right Hyper", Keys.RightHyper },

		{ "CapsLock", Keys.CapsLock },
		{ "F1", Keys.F1 },
		{ "F2", Keys.F2 },
		{ "F3", Keys.F3 },
		{ "F4", Keys.F4 },
		{ "F5", Keys.F5 },
		{ "F6", Keys.F6 },
		{ "F7", Keys.F7 },
		{ "F8", Keys.F8 },
		{ "F9", Keys.F9 },
		{ "F10", Keys.F10 },
		{ "F11", Keys.F11 },
		{ "F12", Keys.F12 },
		{ "PrintScreen", Keys.PrintScreen },
		{ "ScrollLock", Keys.ScrollLock },
		{ "Pause", Keys.Pause },
		{ "Insert", Keys.Insert },
		{ "Home", Keys.Home },
		{ "PageUp", Keys.PageUp },
		{ "End", Keys.End },
		{ "PageDown", Keys.PageDown },
		{ "Right", Keys.Right },
		{ "Left", Keys.Left },
		{ "Down", Keys.Down },
		{ "Up", Keys.Up },
		{ "Numlock", Keys.NumLock },

		{ "Keypad /", Keys.KeypadSlash },
		{ "Keypad *", Keys.KeypadAsterisk },
		{ "Keypad -", Keys.KeypadMinus },
		{ "Keypad +", Keys.KeypadPlus },
		{ "Keypad Enter", Keys.KeypadEnter },

		{ "Keypad 1", Keys.Keypad1 },
		{ "Keypad 2", Keys.Keypad2 },
		{ "Keypad 3", Keys.Keypad3 },
		{ "Keypad 4", Keys.Keypad4 },
		{ "Keypad 5", Keys.Keypad5 },
		{ "Keypad 6", Keys.Keypad6 },
		{ "Keypad 7", Keys.Keypad7 },
		{ "Keypad 8", Keys.Keypad8 },
		{ "Keypad 9", Keys.Keypad9 },
		{ "Keypad 0", Keys.Keypad0 },
		{ "Keypad .", Keys.KeypadDot },

		{ "Menu", Keys.Menu },
		{ "Power", Keys.Power },
		{ "Keypad =", Keys.KeypadEqual },

		{ "F13", Keys.F13 },
		{ "F14", Keys.F14 },
		{ "F15", Keys.F15 },
		{ "F16", Keys.F16 },
		{ "F17", Keys.F17 },
		{ "F18", Keys.F18 },
		{ "F19", Keys.F19 },
		{ "F20", Keys.F20 },
		{ "F21", Keys.F21 },
		{ "F22", Keys.F22 },
		{ "F23", Keys.F23 },
		{ "F24", Keys.F24 },

		{ "Execute", Keys.Execute },
		{ "Help", Keys.Help },
		{ "Select", Keys.Select },
		{ "Stop", Keys.Stop },
		{ "Again", Keys.Again },
		{ "Undo", Keys.Undo },
		{ "Cut", Keys.Cut },
		{ "Copy", Keys.Copy },
		{ "Paste", Keys.Paste },
		{ "Find", Keys.Find },
		{ "Mute", Keys.Mute },
		{ "VolumeUp", Keys.VolumeUp },
		{ "VolumeDown", Keys.VolumeDown },

		{ "Keypad ,", Keys.KeypadComma },

		{ "AltErase", Keys.AltErase },
		{ "SysReq", Keys.SysReq },
		{ "Cancel", Keys.Cancel },
		{ "Clear", Keys.Clear },
		{ "Prior", Keys.Prior },
		{ "Separator", Keys.Separator },
		{ "Out", Keys.Out },
		{ "Oper", Keys.Oper },
		{ "Clear / Again", Keys.ClearAgain },
		{ "CrSel", Keys.Csel },
		{ "ExSel", Keys.Exsel },

		{ "Keypad 00", Keys.Keypad00 },
		{ "Keypad 000", Keys.Keypad000 },
		{ "ThousandsSeparator", Keys.ThousandsSeparator },
		{ "DecimalSeparator", Keys.DecimalSeparator },
		{ "CurrencyUnit", Keys.CurrencyUnit },
		{ "CurrencySubUnit", Keys.CurrencySubUnit },

		{ "Keypad (", Keys.KeypadLeftParen },
		{ "Keypad )", Keys.KeypadRightParen },
		{ "Keypad {", Keys.KeypadLeftBrace },
		{ "Keypad }", Keys.KeypadRightBrace },

		{ "Keypad Tab", Keys.KeypadTab },
		{ "Keypad Backspace", Keys.KeypadBackspace },

		{ "Keypad A", Keys.KeypadA },
		{ "Keypad B", Keys.KeypadB },
		{ "Keypad C", Keys.KeypadC },
		{ "Keypad D", Keys.KeypadD },
		{ "Keypad E", Keys.KeypadE },
		{ "Keypad F", Keys.KeypadF },

		{ "Keypad XOR", Keys.KeypadXor },
		{ "Keypad ^", Keys.KeypadCaret },
		{ "Keypad %", Keys.KeypadPercent },
		{ "Keypad <", Keys.KeypadLessThan },
		{ "Keypad >", Keys.KeypadGreaterThan },
		{ "Keypad &", Keys.KeypadAnd },
		{ "Keypad &&", Keys.KeypadAndAnd },
		{ "Keypad |", Keys.KeypadPipe },
		{ "Keypad ||", Keys.KeypadPipePipe },
		{ "Keypad :", Keys.KeypadColon },
		{ "Keypad #", Keys.KeypadHash },
		{ "Keypad Space", Keys.KeypadSpace },
		{ "Keypad @", Keys.KeypadAt },
		{ "Keypad !", Keys.KeypadExclamation },

		{ "Keypad MemStore", Keys.KeypadMemStore },
		{ "Keypad MemRecall", Keys.KeypadMemRecall },
		{ "Keypad MemClear", Keys.KeypadMemClear },
		{ "Keypad MemAdd", Keys.KeypadMemAdd },
		{ "Keypad MemSubtract", Keys.KeypadMemSubtract },
		{ "Keypad MemMultiply", Keys.KeypadMemMultiply },
		{ "Keypad MemDivide", Keys.KeypadMemDivide },

		{ "Keypad +/−", Keys.KeypadPlusMinus },
		{ "Keypad Clear", Keys.KeypadClear },
		{ "Keypad ClearEntry", Keys.KeypadClearEntry },

		{ "Keypad Binary", Keys.KeypadBinary },
		{ "Keypad Octal", Keys.KeypadOctal },
		{ "Keypad Decimal", Keys.KeypadDecimal },
		{ "Keypad Hexadecimal", Keys.KeypadHex },

		{ "Left Ctrl", Keys.LeftCtrl },
		{ "Left Shift", Keys.LeftShift },
		{ "Left Alt", Keys.LeftAlt },
		{ "Left Windows", Keys.LeftWindows },
		{ "Right Ctrl", Keys.RightCtrl },
		{ "Right Shift", Keys.RightShift },
		{ "Right Alt", Keys.RightAlt },
		{ "Right Windows", Keys.RightWindows },

		{ "ModeSwitch", Keys.ModeSwitch },
		{ "Sleep", Keys.Sleep },
		{ "Wake", Keys.Wake },

		{ "ChannelUp", Keys.ChannelUp },
		{ "ChannelDown", Keys.ChannelDown },

		{ "MediaPlay", Keys.MediaPlay },
		{ "MediaPause", Keys.MediaPause },
		{ "MediaRecord", Keys.MediaRecord },
		{ "MediaFastForward", Keys.MediaFastForward },
		{ "MediaRewind", Keys.MediaRewind },
		{ "MediaTrackNext", Keys.MediaTrackNext },
		{ "MediaTrackPrevious", Keys.MediaTrackPrevious },
		{ "MediaStop", Keys.MediaStop },
		{ "Eject", Keys.Eject },
		{ "MediaPlayPause", Keys.MediaPlayPause },
		{ "MediaSelect", Keys.MediaSelect },

		{ "AC New", Keys.AcNew },
		{ "AC Open", Keys.AcOpen },
		{ "AC Close", Keys.AcClose },
		{ "AC Exit", Keys.AcExit },
		{ "AC Save", Keys.AcSave },
		{ "AC Print", Keys.AcPrint },
		{ "AC Properties", Keys.AcProperties },
		{ "AC Search", Keys.AcSearch },
		{ "AC Home", Keys.AcHome },
		{ "AC Back", Keys.AcBack },
		{ "AC Forward", Keys.AcForward },
		{ "AC Stop", Keys.AcStop },
		{ "AC Refresh", Keys.AcRefresh },
		{ "AC Bookmarks", Keys.AcBookmarks },

		{ "SoftLeft", Keys.SoftLeft },
		{ "SoftRight", Keys.SoftRight },

		{ "Call", Keys.Call },
		{ "EndCall", Keys.EndCall }
	};
}