<Project Sdk="Microsoft.NET.Sdk">

   <PropertyGroup>
		<EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
        <TargetFramework>netstandard2.0</TargetFramework>
        <IncludeBuildOutput>false</IncludeBuildOutput>
        <LangVersion>latest</LangVersion>
        <Nullable>disable</Nullable>
        <IsPackable>true</IsPackable>
        <ImplicitUsings>disable</ImplicitUsings>
    </PropertyGroup>

   <ItemGroup>
     <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Scripting" Version="5.3.0" />
   </ItemGroup>

</Project>
